# Generated by Django 4.2.4 on 2023-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11)),
                ('work_line', models.CharField(choices=[('Baker', 'Baker'), ('Beat Maker', 'Beat Maker'), ('Jeweler', 'Jeweler'), ('Lawyer', 'Lawyer'), ('Stripper', 'Stripper'), ('None', 'Is None')], default='None', max_length=256)),
                ('interest', models.CharField(max_length=256)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('area_code', models.CharField(max_length=6)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
            ],
        ),
    ]
